name: renovasim
description: RenovaSim - AI-powered home renovation planning app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  webview_flutter: ^4.4.0
  http: ^1.1.0
  image_picker: ^1.0.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: PPEditorialNew
    fonts:
      - asset: assets/fonts/PP-Editorial-New/PPEditorialNew-Regular-BF644b214ff145f.otf
      - asset: assets/fonts/PP-Editorial-New/PPEditorialNew-Italic-BF644b214fb0c0a.otf
        style: italic

  - family: PPNeueMontrealMedium
    fonts:
      - asset: assets/fonts/PP-Neue-Montreal/ppneuemontreal-medium.otf
      - asset: assets/fonts/PP-Neue-Montreal/ppneuemontreal-bold.otf
        weight: 700